#Create VPC Using Cloud Formation Using yaml 
AWSTemplateFormatVersion: 2010-09-09 
Description: Creates a VPC with public and private subnets and EC2 instances. 
Resources: 
  CFVPC: 
    Type: 'AWS::EC2::VPC' 
    Properties: 
      CidrBlock: 10.0.0.0/16 
      EnableDnsSupport: true 
      EnableDnsHostnames: true 
      Tags: 
        - Key: Name 
          Value: CFVPC 
  PublicSubnet: 
    Type: 'AWS::EC2::Subnet' 
    Properties: 
      VpcId: !Ref CFVPC 
      CidrBlock: 10.0.1.0/24 
      MapPublicIpOnLaunch: true 
      Tags: 
        - Key: Name 
          Value: PublicSubnet 
  PrivateSubnet: 
    Type: 'AWS::EC2::Subnet' 
    Properties: 
      VpcId: !Ref CFVPC 
      CidrBlock: 10.0.2.0/24 
      Tags: 
        - Key: Name 
          Value: PrivateSubnet 
  InternetGateway: 
    Type: 'AWS::EC2::InternetGateway' 
  AttachGateway: 
    Type: 'AWS::EC2::VPCGatewayAttachment' 
    Properties: 
      VpcId: !Ref CFVPC 
      InternetGatewayId: !Ref InternetGateway 
  RouteTable: 
    Type: 'AWS::EC2::RouteTable' 
    Properties: 
      VpcId: !Ref CFVPC 
  PublicRoute: 
    Type: 'AWS::EC2::Route' 
    DependsOn: AttachGateway
    Properties: 
      RouteTableId: !Ref RouteTable 
      DestinationCidrBlock: 0.0.0.0/0 
      GatewayId: !Ref InternetGateway 
  AssociatePublicSubnetRouteTable: 
    Type: 'AWS::EC2::SubnetRouteTableAssociation' 
    Properties: 
      SubnetId: !Ref PublicSubnet 
      RouteTableId: !Ref RouteTable 
  PublicInstance: 
    Type: 'AWS::EC2::Instance' 
    Properties: 
      InstanceType: t3.micro 
      ImageId: 'ami-0449c34f967dbf18a' 
      SubnetId: !Ref PublicSubnet 
      KeyName : 'mumbai' 
      Tags: 
        - Key: Name 
          Value: Public-Instance 
  PrivateInstance: 
    Type: 'AWS::EC2::Instance' 
    Properties: 
      InstanceType: t3.micro 
      ImageId: 'ami-0449c34f967dbf18a' 
      SubnetId: !Ref PrivateSubnet 
      KeyName : 'mumbai' 
      Tags: 
        - Key: Name 
          Value: Private-Instance 
Outputs: 
  VPCId: 
    Value: !Ref CFVPC 
  PublicSubnetId: 
    Value: !Ref PublicSubnet 
  PrivateSubnetId: 
    Value: !Ref PrivateSubnet 
  PublicInstanceId: 
    Value: !Ref PublicInstance 
  PrivateInstanceId: 
    Value: !Ref PrivateInstance